### PR TITLE
Painter redesign

### PR DESCRIPTION
**Pull request by MrRar**
This PR redisgns the automobile painter to have a better UI and update the automobile color directly. Punch an automobile and and the painter formspec comes up initialized with the automobile's color. Move the sliders or manually enter a hex code. Press set color and the automobile's color is updated. Only the owner can paint an automobile.

painter

### CODE REVIEW

**Comment by APercy** [comment]
The problem is that will do not work with the airplanes, as it turned specific for the cars. And I want to keep painting my planes with more interesting colors :)

**Comment by MrRar** [comment]
@APercy I will try adding _on_paint hooks to everything later.

**Comment by MrRar** [comment]
@APercy I changed the painter so it can work with any entity that has a _change_color hook. I made PRs to add this hook to a bunch of your airplanes. Hopefully I got all of them.

**Comment by APercy** [comment]
perfect! I added the same code to the trike and it worked like a charm

**Comment by MrRar** [comment]
Oops! I guess I forgot to make a PR for the trike. I even forked and modified it.

**Comment by APercy** [comment]
relax, I did it myself yesterday :)

**Pull request merged**
